---
title: "Themen"
author: "Jan-Philipp Kolb"
date: "11 Juni 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wie bekommt man Hilfe 

- Foren, Blogs und Supportmöglichkeiten

## 

- Wie gehe ich mit Variablen-Label/Value-Label um? D.h.: wie erstelle ich sie, wie greife ich darauf wieder zu, wie mache ich sie in Grafiken/Tabellen rein?
- Wie genau ist das mit missing values in R? (Können die eigentlich auch Valuelabel haben?)


- Mein konkretes Ziel: Wie kann ich eine Kreuztabelle mit R erstellen
(mit Value und Variablenlabel)?


## Präsentationen

- Entscheidungshilfe slidy vs. ioslides
 
 
## Rekodieren 


## Labeln, Schleifenprogrammierung
 
Scatterplots, Plots von Koeffizienten/marginalen Effekten/predicted probabilities 

## Zusammenfassung

- Zusammenfassung mit den wichtigsten/nützlichsten R-Paketen
 
 
## Pausen

- längere Mittagspause
- mehrere kürzere Pausen


## Links

- [Spatial R](http://slideplayer.com/slide/6133281/)