---
title: "Datenaufbereitung"
author: "Jan-Philipp Kolb"
date: "21 Juni 2017"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## [Variablen Labels](https://stackoverflow.com/questions/2151147/using-stata-variable-labels-in-r)

```{r}
library(foreign)
dat <- read.dta("https://github.com/Japhilko/RSocialScience/blob/master/data/GPanel.dta?raw=true")
```

```{r}
var.labels <- attr(dat,"var.labels")
```

## Ein Überblick

```{r}
nrow(dat)
ncol(dat)
```

```{r}
head(dat)
```


## Indizieren

- Das Dollarzeichen kann man nutzen um einzelne Spalten anzusprechen

```{r}
head(dat$a11c019a)

dat$a11c019a[1:10]
```

- Man kann auch Zahlen nutzen um auf die Spalten zuzugreifen

```{r}
head(dat[,1])
```

## Datentypen

```{r}
# as.numeric()
```


## [Rekodieren](https://www.r-bloggers.com/recoding-variables-in-r-pedagogic-considerations/)

```{r}
library(car)
?recode
```


## [Exkurs - Labels wie verwenden]()

```{r}
library("forcats")
browseVignettes()
```


```{r}
library(tibble)

gpanel1 <- as_tibble(gpanel)

head(gpanel1)
```

## Schleifen

```{r}
erg <- vector()

for (i in 1:ncol(dat)){
  erg[i] <- length(table(dat[,i]))  
}
```



## Fehlende Werte

```{r}
dat$bazq020a[dat$bazq020a==-99] <- NA
```




- [Quick-R zu fehlenden Werten](http://www.statmethods.net/input/missingdata.html)

- [Fehlende Werte rekodieren](http://uc-r.github.io/na_recode)
