---
title: "Multilevel"
author: "Jan-Philipp Kolb"
date: "12 Mai 2017"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basis Regression

- [How to go about interpreting regression cofficients](https://www.r-bloggers.com/how-to-go-about-interpreting-regression-cofficients/)


## [Ein Beispieldatensatz](https://www.jaredknowles.com/journal/2013/11/25/getting-started-with-mixed-effect-models-in-r)

```{r,eval=F}
install.packages("lme4")

# Or to install the dev version
library(devtools)
install_github("lme4", user = "lme4")
```

## [Multilevel Modeling of Educational Data using R (Part 1)](https://www.r-bloggers.com/multilevel-modeling-of-educational-data-using-r-part-1/)

- [Original Blogg](http://hagutierrezro.blogspot.de/2016/10/multilevel-modeling-of-educational-data.html)

```{r,eval=F}
install.packages("lme4")
install.packages("sjPlot")
```



```{r}
library(ggplot2)
library(gridExtra)
library(lme4)
library(sjPlot)
library(dplyr)

set.seed(123)
```

```{r}
N <- 100 #Number of students per school
sigma <- 200

x1 <- runif(N, 10, 40)
x2 <- runif(N, 25, 55)
x3 <- runif(N, 40, 70)
x4 <- runif(N, 55, 85)
x5 <- runif(N, 70, 100)
```

```{r}
y1 <- 20 + 0 * x1 + rnorm(N, 0, sigma)
y2 <- 40 + 10 * x2 + rnorm(N, 0, sigma)
y3 <- 60 + 20 * x3 + rnorm(N, 0, sigma)
y4 <- 80 + 30 * x4 + rnorm(N, 0, sigma)
y5 <- 100 + 40 * x5 + rnorm(N, 0, sigma)

ID <- rep(LETTERS[1:5], each = N)

test <- data.frame(SES = c(x1, x2, x3, x4, x5), 
 Score = c(y1, y2, y3, y4, y5), ID = ID)
```


```{r}
HLM0 <- lmer(Score ~ (1 | ID), data = test)
coef(HLM0)
summary(HLM0)

# 96% - Between-schools variance
# 4% - Within-schools variance
100 * 87346 / (87346 + 1931757)
```


```{r}
HLM1 <- lmer(Score ~ SES + (SES | ID), data = test)
coef(HLM1)
summary(HLM1)

# 1% - BS variance
# 99% - WS variance
100 * 40400.24 / (40400.24 + 257.09 + 1.65)

# Percentage of variation explained by SES between schools
1 - ((257.09 + 1.65) / 1931757)

# Percentage of variation explained by SES within schools
1 - (40400.24 / 87346)
```


## Links

- [Uncertainty in parameter estimates using multilevel models](https://www.r-bloggers.com/uncertainty-in-parameter-estimates-using-multilevel-models/)

## [Multilevel models with R](https://cran.r-project.org/doc/contrib/Bliese_Multilevel.pdf)

## [Paket lmer](https://cran.r-project.org/doc/contrib/Bliese_Multilevel.pdf)





```{r,eval=F}
lmer(y ~ 1 + (1 | subjects), data=data)
# nlme
lme(y ~ 1, random = ~ 1 | subjects, data=data)
```

