---
title: "index"
author: "Jan-Philipp Kolb"
date: "12 Mai 2017"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## [Erste Schritte Datenimport](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_1.md) 

- Komplette Folien zum ersten Kapitel Datenimport als [pdf](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_1.pdf)

- [Einführung und Motivation](https://github.com/Japhilko/RInterfaces/blob/master/slides/Intro.md) 

- Einführungsfolien als [pdf](https://github.com/Japhilko/RInterfaces/blob/master/slides/Intro.pdf)

- Aufgabe: [Zusatzpakete](https://github.com/Japhilko/RInterfaces/blob/master/tutorial/Aufgabe_Zusatzpakete.md)

[Datenimport](https://github.com/Japhilko/RInterfaces/blob/master/slides/Datenimport.md) 

- ([pdf](https://github.com/Japhilko/RInterfaces/blob/master/slides/Datenimport.pdf)   [rcode](https://github.com/Japhilko/RInterfaces/blob/master/slides/Datenimport.R))

- Aufgabe: [Datenimport](tutorial/Aufgabe_Datenimport.md)

[Datenexport](slides/Datenexport.md) 

- ([pdf](slides/Datenexport.pdf)   [rcode](slides/Datenexport.R)) 

[R und Excel](slides/Rexcel.md) 

- ([pdf](slides/Rexcel.pdf)   [rcode](slides/Rexcel.R))

- Aufgabe: [Export nach Excel](tutorial/Aufgabe_Export2Excel.md)

## [Präsentation von Daten - Reproducible Research](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_2.md) 

- ([pdf](slides/RInterfaces_all2g_2.pdf))

[Word Dokumente mit R erstellen](slides/R2word.md) 

- ([pdf](slides/R2word.pdf))

[PDF Dokumente und Präsentationen mit LaTeX, Beamer und Sweave](slides/R2pdf.md) 

- ([pdf](slides/R2pdf.pdf))

[HTML Dokumente, Präsentationen und Dashboards mit Rmarkdown](slides/Rmarkdown.md) 

- ([pdf](slides/Rmarkdown.pdf))

[Notebooks](slides/Notebooks.md) zur Integration von anderen Programmiersprachen (Python,LaTeX,Julia) 

- ([pdf](slides/Notebooks.pdf))

- Aufgabe: [Bearbeiten Sie ein Notebook weiter](tutorial/Aufgabe_Notebook.md)


## Liebe auf den ersten Plot – Grafiken mit R	

[Einfache Grafiken](https://github.com/Japhilko/IntroR/blob/master/2017/slides/EinfacheGrafiken.md) 

- [pdf](slides/EinfacheGrafiken.pdf)   
- [rcode](rcode/EinfacheGrafiken.R)
- [Aufgabe - Barplot](https://github.com/Japhilko/IntroR/blob/master/2017/tutorial/Aufgabe_Barplot.md))
    


## Noch mehr Grafiken - multidimensional

[Zusammenhang](https://github.com/Japhilko/IntroR/blob/master/2017/slides/Multidimensional.md)

- [pdf](slides/Multidimensional.pdf)   
- [rcode](rcode/Multidimensional.R))

[Das lattice Paket](https://github.com/Japhilko/IntroR/blob/master/2017/slides/LatticePaket.md)   

- [pdf](slides/LatticePaket.pdf)   
- [rcode](rcode/LatticePaket.R))
- Aufgabe - OECD Datensatz ([Browser](https://github.com/Japhilko/IntroR/blob/master/2017/slides/Aufgabe_OECDdata.md))
    


## Intro Regression 

[Die lineare Regression](https://github.com/Japhilko/IntroR/blob/master/2017/slides/LineareRegression.md)   

- [pdf](https://github.com/Japhilko/IntroR/blob/master/2017/slides/LineareRegression.pdf)   
- [rcode](https://github.com/Japhilko/IntroR/blob/master/2017/rcode/LineareRegression.R))

- [Aufgabe - lineare Regression](https://github.com/Japhilko/IntroR/blob/master/2017/tutorial/Aufgabe_LineareRegression.md))

- [Die logistische Regression](https://github.com/Japhilko/IntroR/blob/master/2017/slides/logistischeRegression.md)   

- [pdf](https://github.com/Japhilko/IntroR/blob/master/2017/slides/logistischeRegression.pdf)   
- [rcode](https://github.com/Japhilko/IntroR/blob/master/2017/rcode/logistischeRegression.R)

- Aufgabe - Datenanalyse ([Browser](https://github.com/Japhilko/IntroR/blob/master/2017/tutorial/Aufgabe_Datenanalyse.md))



## [Applikationen und Projektverwaltung mit Rstudio und git](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_5.md) 

- [pdf](slides/RInterfaces_all2g_5.pdf)

[Allgemein zur Versionsverwaltung](slides/Versionsverwaltung.md) 

- [pdf](slides/Versionsverwaltung.pdf)


[R und Git](slides/Rgit.md) 

- [pdf](slides/Rgit.pdf)  
- [rcode](rcode/Rgit.R)

[Shiny Apps](slides/shiny.md) 

- [pdf](slides/shiny.pdf)   
- [rcode](rcode/shiny.R)


## [Interaktive Darstellung mit Javascript und R](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_3.md) 

- [pdf](slides/RInterfaces_all2g_3.pdf)

[Interaktive Karten mit dem Javascript Paket leaflet](https://github.com/Japhilko/RInterfaces/blob/master/slides/leaflet.md) 

- [pdf](slides/leaflet.pdf)   
- [rcode](rcode/leaflet.R))

- Aufgabe: [Eine interaktive Karte erzeugen](tutorial/Aufgabe_leaflet.md)

[Interaktive Tabellen mit DataTables](https://github.com/Japhilko/RInterfaces/blob/master/slides/DataTables.md) 

- [pdf](slides/DataTables.pdf)   
- [rcode](rcode/DataTables.R)

[R und die Javascript Data-Driven Documents (D3)](https://github.com/Japhilko/RInterfaces/blob/master/slides/D3.md) 

- [pdf](slides/D3.pdf)   
- [rcode](rcode/D3.R))

[Interaktive Graphiken mit D3 und plotly](https://github.com/Japhilko/RInterfaces/blob/master/slides/plotly.md) 

- [pdf](slides/plotly.pdf)   
- [rcode](rcode/plotly.R))

[Netzwerkgraphiken mit vis.js](https://github.com/Japhilko/RInterfaces/blob/master/slides/visNetwork.md) 

- [pdf](slides/visNetwork.pdf)   [rcode](rcode/visNetwork.R)


[Das Erstellen von Ablaufdiagrammen mit mermaid](https://github.com/Japhilko/RInterfaces/blob/master/slides/mermaid.md)

- [pdf](slides/mermaid.pdf)   

- [rcode](rcode/mermaid.R))


