---
title: "R für die Sozialwissenschaften - Teil 1"
author: "Jan-Philipp Kolb"
date: "22 Juni 2017"
output: 
  beamer_presentation:
    colortheme: beaver
    highlight: pygments
    theme: CambridgeUS
    fig_caption: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Einführung und Motivation

```{r child = '../intro/index.Rmd'}
```

## Erste Schritte mit R

```{r child = '../ersteSchritte/index.Rmd'}
```


## Wie bekommt man Hilfe

```{r child = '../hilfe/index.Rmd'}
```


## Modularer Aufbau

```{r child = '../Rmodular/index.Rmd'}
```

## Datenimport

```{r child = '../import/index.Rmd'}
```


## Datenaufbereitung

```{r child = '../Datenaufbereitung/index.Rmd'}
```


## Datenexport

```{r child = '../export/index.Rmd'}
```


## Basisgrafiken

```{r child = '../simpleGraphics/index.Rmd'}
```

## Datenanalyse

```{r child = '../Datenanalyse/index.Rmd'}
```

## Grafiken und Zusammenhang

```{r child = '../multidimensional/index.Rmd'}
```

## Das lattice Paket


```{r child = '../lattice/index.Rmd'}
```
